from tkinter import *
root = Tk()
root.geometry('400x220+200+100')
root.title("coder")
root.resizable(False, False)
l1 = Label(text="Write a text")
l1.config(font=("Verdana", 15, 'bold'))
e1 = Entry(width=22)
e1.config(font=("Calibri", 13))
b1 = Button(text="encrypt", padx = 60)
b2 = Button(text="code table", padx = 48)
b1.config(font=("Verdana", 12, 'bold'))
b2.config(font=("Verdana", 12, 'bold'))
l2= Label(text="Encrypted code")
l2.config(font=("Verdana", 15, 'bold'))
l3 =Label(text = "",width=22, bg = "white")
l3.config(font=("Calibri", 13))
l1.pack()
e1.pack()
b1.place(x=99,y=60)
b2.place(x=99,y=95)
l2.place(x=112,y=135)
l3.place(x=98,y=165)
root.mainloop()
